apiVersion: v1
kind: Service
metadata:
  name: fe
  namespace: colombus
  labels:
    app: fe
spec:
  type: ClusterIP
  selector:
    app: fe
  ports:
    - name: http
      port: 8080          # 클러스터 안에서 보는 포트
      targetPort: 8080  # 컨테이너 포트(nginx 8080)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  namespace: colombus
  labels:
    app: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: fe
          image: 970103397792.dkr.ecr.ap-northeast-2.amazonaws.com/colombus/fe:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/runtime-config.js
              subPath: runtime-config.js

          readinessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "256Mi" }

      volumes:
        - name: runtime-config
          secret:
            secretName: fe-app-secret
